### PR TITLE
Do not expect aliases to have a public file

### PR DESCRIPTION
**Pull request by johlju**

### CODE REVIEW

**Comment by johlju** [comment]
With this change I'm getting that GetAliasCommand returns private function aliases. Not sure how we prevent that? Suggestions?

**Comment by Jaykul** [comment]
Well, the old functionality *only* exported aliases if they pointed at **public** functions.

Now we can't do that, because the aliases you're trying to add point at ... other things (files, external functions, whatever).

**Comment by Jaykul** [comment]
Basically, I think we have to either:

1. Export any aliases, regardless of what they point at ...
2. Remove aliases that point at *private* functions (rather than filtering ones that _don't_ point at *public* functions)

I'm leaning toward the first, meaning we just say: don't make aliases to private functions if you don't want them exported 😉

**Comment by johlju** [comment]
Yes I'm good with the first. It could be improved upon later on if that will be a big issue. 🤔

**Pull request closed without merging**
