### PR TITLE
fixing #118 by mandating sort by FullName

### PR DESCRIPTION
**Pull request by gaelcolas**
I used this version as it's simpler and we can always fall back to the more complex approach if we find a need for it.

### CODE REVIEW

**Review by Jaykul — APPROVED** [review]
I was thinking we would leave the call as is, and sort _everything_, but this preserves the existing ability to order folders in the `SourceDirectories` list, so it looks ok.

**Comment by juliamwang6** [comment]
Hi @Jaykul, nice to meet you! I'm a PM on Azure Machine Configuration who will be releasing the nxtools module. Our team is wondering when you are planning on releasing ModuleBuilder, since customers have expressed a lot of interest in nxtools and we'd love to opensource it as soon as possible. Thanks so much!

**Comment by kilasuit** [comment]
@juliamwang6 -ModuleBuilder is already released and available on the PowerShell Gallery

**Comment by Jaykul** [comment]
Not sure I'm following why you needed ModuleBuilder to open source your module, @juliamwang6 😜 but I have fixed my workflow and published this (along with the new Alias stuff) as 3.0.0

**Comment by juliamwang6** [comment]
Awesome! Thanks so much, Joel :)

**Pull request merged**
