### PR TITLE
BREAKING CHANGE: addresses #65 and changes output path calculation

### LINKED ISSUE #30: Build-Module -Target Build -Passthru # does not work
The -Passthru switch doesn't work when the build is skipped because it's already up to date.

### LINKED ISSUE #39: [Documentation] Build-Module parameter -Target
Its possible values are not explained :

> [ValidateSet("Clean", "Build", "CleanBuild")]

Regarding its behavior, should the value Clean delete the versioned directory?
image

build.pds1:
```Powershell
@{
    Path = "MyModule.psd1"
    OutputDirectory = "C:\temp\Delivery\MyModule"
    VersionedOutputDirectory = $true
    CopyDirectories=@('.\Demos','.\fr-FR','.\TypeData')
}
```

### LINKED ISSUE #76: Please document dependency on gitversion
the bootstrap build.ps1 file uses something called `gitversion` which is not listed in RequiredModules and I have no idea what it is or how to get it.

I'm aware of the gitversion project but this `gitversion` uses Powershell style parameter passing but doesn't follow Powershell cmdlet naming functions, and also I can't find any reference to a `showvariable` parameter in the gitversion documentation.  I also can't find anything in the powershell gallery related to gitversion.  Looking through the sourcecode of gitversion there does appear to be a `/showvariable` parameter but it also requires `/output json` which isn't being specified here so I don't think this is just merely the gitversion executable.

And IF IT IS just the gitversion executable, that needs to be called out in the documentation.

### LINKED ISSUE #93: Prerelease Key being stripped
I have a module with Prerelease = "alpha" set in the manifest. This value is being stripped out on build. I attempted to set this value using the `-Prerelease` parameter, but I'm still left with an empty value after build.

### LINKED ISSUE #99: [Documentation] Update step 2. Install dependencies
README [Step 2](https://github.com/PoshCode/ModuleBuilder#2-install-dependencies) instructs a new user to "2. Install dependencies" via `.\Install-RequiredModule.ps1`, but this project (no longer?) includes the specified file.

### PR DESCRIPTION
**Pull request by Jaykul**
A bunch of minor changes:
- Fixes #76 by updating the documentation
- Fixes #39 by adding documentation
- Fixes #99 by putting back the helpful Install-RequiredModule wrapper
- Fixes #30 so -Passthru works when the build is skipped
- Fixes #93 to only change PreRelease if -Semver or -Prerelease are explicitly passed

### CODE REVIEW

**Comment by Jaykul** [comment]
Since this changes the rules about WHERE the module builds to, it's obviously a breaking change, but I think it's pretty minor since it doesn't actually change the output, just where it goes.

However (aside from sticking in the minor fixes) this ended up being a larger changeset than I expected because the changes to the output location affected a lot of tests -- and a lot of them were already not passing on Linux & Mac OS.

**Comment by Jaykul** [comment]
I've been thinking that if I'm going to have a breaking change to the output location, maybe I want to _default_ to `Output\ModuleName\Version` instead of `Output\ModuleName` and get rid of the `-VersionedOutputFolder` and replace it with `-NoVersionFolder` ....

Thoughts? Anyone?

**Comment by kilasuit** [comment]
Is this primarily so that you can have build iterations locally and do better side by side debugging as you are making changes to a module?

If so I can see where this would be useful as long as you didn't just wipe out the `output\modulename` folder

**Comment by Jaykul** [comment]
In the current released version, if you do something stupid, like:
```PowerShell
Build-Module -OutputPath C:\ -Target Clean
```

It will ... delete everything on C:\

So far, this changeset makes it so that it [calculates an OutputDirectory](https://github.com/PoshCode/ModuleBuilder/pull/98/files#diff-868b17c1d44b8dfac19e941eaf9b74f4)
  - It adds "ModuleName" to the `OutputDirectory` you specify (which defaults to `..\Output)
  - If you pass a path that already ends in ModuleName, it isn't added again.
  - If you pass a path that's a parent of source, it adds the version number (this is to account for building from ModuleName\Source to ModuleName)

What I'm proposing to add further is that VersionedOutputFolder would default to on, so you'd (by default) get `..\Output\ModuleName\Version`

**Comment by Jaykul** [comment]
I didn't feel like I got a lot of feedback one way or the other, so I've released two pre-release builds:

The first one is version "2.0.0-ModuleName" which represents the original PR at [20610d8](https://github.com/PoshCode/ModuleBuilder/commit/20610d8c5da137a3b6a6cdb13a9cfec74915c9f6) from two weeks ago.

The second one is version "2.0.0-VersionedOutput" which represents the current state, and includes the change to deprecate `VersionedOutputFolder` and have it default to true. It also adds a new `UnversionedOutputFolder` option that supports building without the forced version number folder (the old default), in case anyone really hates this change but doesn't speak up now...

**Pull request merged**
