### PR TITLE
Adds a note explaining what 'Source\build.js' is for

### PR DESCRIPTION
**Pull request by bravo-kernel**
A small note to help (new) developers understand what the file is intended for.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Not sure the failing build is related. Will look closer one of these days.

**Comment by Jaykul** [comment]
Don't worry about it, I'm working on fixing the build, and I'll pull your change after I get it sorted out

**Comment by Jaykul** [comment]
Test comment

**Comment by bravo-kernel** [comment]
I could not find a quick fix for the build but did add one more commit. Hope it makes sense.

**Comment by bravo-kernel** [comment]
@Jaykul I managed to solve the azure prerequisite step by copying the fixes I applied in my repo, that step should turn green now.

Then next build step however, to my surprise, fails.

**Comment by bravo-kernel** [comment]
@Jaykul The pipeline has been fixed so please merge. If I am not mistaken the other PRs should now turn green as well after re-triggering the builds. IMO this paves the way for constructive step-by-step improvements. This needs to go super-stable and predictable. 👍

**Comment by bravo-kernel** [comment]
PS: this is probably obvious but the solution was two-fold:

- Installing the NuGet PackageProvider
- Using the local `Install-Module.ps` instead of the one fetched using `Install-Script` (could not yet check but I am guessing there a differences between them)

**Comment by bravo-kernel** [comment]
OK, to round this up:
- I found the error in the downloaded script. After uncommenting line 208 (in script version 4.0.5) azure completes installing the prerequisites successfully. 
- the big question for me is... where does that downloaded version 4.0.5 come from? I took the source from the PSGallery but could not find any matching source/repo

Before merging I see two options:
1. you fix the downloadable script, I then adjust this PR to start using it again, then merge
2. merge this first, fix and update later

What do you think?

**Comment by bravo-kernel** [comment]
@Jaykul not trying to pressure here could you indicate when that line-fix could rought be expected? I have a bunch of changes and PRs awaiting that fix.

**Comment by Jaykul** [comment]
Yeah, the double -verbose thing was embarrassing -- I finally fixed it for work and published 4.0.6 of that yesterday (and checked it in here too, but in the feature/RequiredModuleDestination branch).

I'm merging this regardless of the failure.

**Comment by Jaykul** [comment]
Ugh. Ok. Noted: the `Rebase and Merge` option is not what I want in the future.

**Comment by bravo-kernel** [comment]
Thanks 👍

**Pull request merged**
